/**
 * Environment File Generator — Config & Secrets Separation
 *
 * Generates .env.example with placeholder values (safe to commit)
 * and .env template with NovaServe resource bindings.
 * Never writes real secret values to disk.
 */

import type { Resource } from "novaserve-core";
import type { DockerDeploymentContext } from "../types.js";

/** Known secret resource names/patterns */
const SECRET_PATTERNS = [
  "password", "secret", "key", "token", "credential",
  "private", "api_key", "apikey", "jwt", "auth",
];

/**
 * Generate .env.example content (safe to commit to git).
 * Contains placeholder values for all environment variables.
 */
export function generateEnvExample(
  ctx: DockerDeploymentContext,
  resources: Resource[]
): string {
  const lines: string[] = [];

  lines.push(`# ─────────────────────────────────────────────────────────`);
  lines.push(`# ${ctx.appName} — Environment Configuration`);
  lines.push(`# Generated by NovaServe Docker Provider`);
  lines.push(`#`);
  lines.push(`# Copy this file to .env and fill in real values:`);
  lines.push(`#   cp .env.example .env`);
  lines.push(`#`);
  lines.push(`# WARNING: Never commit .env to version control!`);
  lines.push(`# ─────────────────────────────────────────────────────────`);
  lines.push(``);

  // ── Application Config ──────────────────────────────────
  lines.push(`# ── Application ────────────────────────────────────────`);
  lines.push(`NODE_ENV=production`);
  lines.push(`PORT=3000`);
  lines.push(`LOG_LEVEL=info`);
  lines.push(``);

  // ── Database Config ─────────────────────────────────────
  const databases = resources.filter((r) => r.type === "database");
  if (databases.length > 0) {
    lines.push(`# ── Database ──────────────────────────────────────────`);
    for (const db of databases) {
      const prefix = databases.length > 1 ? `${db.name.toUpperCase()}_` : "";
      const engine = (db.config.engine as string) || "postgres";
      const defaultPort = engine === "mysql" ? 3306 : engine === "mongodb" ? 27017 : 5432;
      lines.push(`${prefix}DB_HOST=localhost`);
      lines.push(`${prefix}DB_PORT=${defaultPort}`);
      lines.push(`${prefix}DB_NAME=novaserve`);
      lines.push(`${prefix}DB_USER=novaserve`);
      lines.push(`${prefix}DB_PASSWORD=<CHANGE_ME>`);
      if (engine === "postgres" || engine === "mysql") {
        lines.push(`${prefix}DATABASE_URL=${engine === "postgres" ? "postgresql" : "mysql"}://novaserve:<CHANGE_ME>@localhost:${defaultPort}/novaserve`);
      }
      lines.push(``);
    }
  }

  // ── Cache Config ────────────────────────────────────────
  const caches = resources.filter((r) => r.type === "cache");
  if (caches.length > 0) {
    lines.push(`# ── Cache ─────────────────────────────────────────────`);
    for (const cache of caches) {
      const prefix = caches.length > 1 ? `${cache.name.toUpperCase()}_` : "";
      lines.push(`${prefix}REDIS_URL=redis://localhost:6379`);
      lines.push(``);
    }
  }

  // ── Storage Config ──────────────────────────────────────
  const storages = resources.filter((r) => r.type === "storage");
  if (storages.length > 0) {
    lines.push(`# ── Storage ───────────────────────────────────────────`);
    for (const storage of storages) {
      const prefix = storages.length > 1 ? `${storage.name.toUpperCase()}_` : "";
      lines.push(`${prefix}STORAGE_ENDPOINT=http://localhost:9000`);
      lines.push(`${prefix}STORAGE_ACCESS_KEY=<CHANGE_ME>`);
      lines.push(`${prefix}STORAGE_SECRET_KEY=<CHANGE_ME>`);
      lines.push(`${prefix}STORAGE_BUCKET=${storage.name}`);
      lines.push(``);
    }
  }

  // ── Queue Config ────────────────────────────────────────
  const queues = resources.filter((r) => r.type === "queue");
  if (queues.length > 0) {
    lines.push(`# ── Queue ─────────────────────────────────────────────`);
    for (const queue of queues) {
      const prefix = queues.length > 1 ? `${queue.name.toUpperCase()}_` : "";
      lines.push(`${prefix}QUEUE_URL=<QUEUE_CONNECTION_URL>`);
      lines.push(``);
    }
  }

  // ── Secrets ─────────────────────────────────────────────
  const secrets = resources.filter((r) => r.type === "secret");
  if (secrets.length > 0) {
    lines.push(`# ── Secrets (NEVER commit real values) ────────────────`);
    for (const secret of secrets) {
      const envName = secretToEnvName(secret.name);
      lines.push(`${envName}=<CHANGE_ME>`);
    }
    lines.push(``);
  }

  return lines.join("\n");
}

/**
 * Generate .env template content with Docker Compose service bindings.
 * This version uses Docker Compose service names for internal networking.
 */
export function generateEnvTemplate(
  ctx: DockerDeploymentContext,
  resources: Resource[],
  bundleDependencies: boolean
): string {
  const lines: string[] = [];

  lines.push(`# NovaServe Docker Environment — ${ctx.appName}`);
  lines.push(`# Auto-generated. Customize as needed.`);
  lines.push(``);
  lines.push(`NODE_ENV=production`);
  lines.push(`PORT=3000`);
  lines.push(`LOG_LEVEL=info`);
  lines.push(``);

  // If bundling dependencies, use Docker Compose service names
  const databases = resources.filter((r) => r.type === "database");
  for (const db of databases) {
    const engine = (db.config.engine as string) || "postgres";
    const svcName = bundleDependencies ? `${ctx.projectName}-${db.name}` : "localhost";
    const defaultPort = engine === "mysql" ? 3306 : engine === "mongodb" ? 27017 : 5432;
    const prefix = databases.length > 1 ? `${db.name.toUpperCase()}_` : "";

    if (bundleDependencies) {
      lines.push(`${prefix}DB_HOST=${svcName}`);
      lines.push(`${prefix}DB_PORT=${defaultPort}`);
      lines.push(`${prefix}DB_NAME=novaserve`);
      lines.push(`${prefix}DB_USER=novaserve`);
      lines.push(`${prefix}DB_PASSWORD=changeme  # CHANGE IN PRODUCTION`);
      if (engine === "postgres" || engine === "mysql") {
        lines.push(`${prefix}DATABASE_URL=${engine === "postgres" ? "postgresql" : "mysql"}://novaserve:changeme@${svcName}:${defaultPort}/novaserve`);
      }
    }
    lines.push(``);
  }

  const caches = resources.filter((r) => r.type === "cache");
  for (const cache of caches) {
    const svcName = bundleDependencies ? `${ctx.projectName}-${cache.name}` : "localhost";
    const prefix = caches.length > 1 ? `${cache.name.toUpperCase()}_` : "";
    lines.push(`${prefix}REDIS_URL=redis://${svcName}:6379`);
    lines.push(``);
  }

  const secrets = resources.filter((r) => r.type === "secret");
  for (const secret of secrets) {
    const envName = secretToEnvName(secret.name);
    lines.push(`${envName}=  # Set this secret at deployment time`);
  }
  if (secrets.length > 0) lines.push(``);

  return lines.join("\n");
}

/**
 * Classify an environment variable as config or secret.
 */
export function isSecret(name: string): boolean {
  const lower = name.toLowerCase();
  return SECRET_PATTERNS.some((pattern) => lower.includes(pattern));
}

/**
 * Convert a secret resource name to environment variable name.
 */
function secretToEnvName(name: string): string {
  return name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
}
